# Document de conception

## Système

#### Agents

##### Attributs

In [1]:
renard(âge, sexe, efficacité, fécondité, position, faim, excitation)
    renard = {"âge" : int, "sexe" : bool, "efficacité" : rand(), "fécondité" : rand(), (position_x, position_y), "faim" : float, "excitation" : float}
    renards = [renard1, renard2, renard3, renard4, renard5, ...]
lapin(âge, sexe, fécondité, position, faim)
    lapin = {"âge" : int, "sexe" : bool, "fécondité" : rand()}
    lapins = [lapin1, lapin2, lapin3, lapin4, lapin5, ...]

IndentationError: unexpected indent (<ipython-input-1-16bb1b73cae9>, line 2)

##### Procédures

In [3]:
reproduction_des_renards(renard1, renard2):
    """Si deux renards sont sur la même case, cette fonction s'enclenche et fait apparaître des renardeaux sur la même case d'age 0"""
    if renard1["sexe"] != renard2["sexe"]: #On vérifie si le sexe des deux renards est différent
        if 0.5 <= (renard1["fécondité"]+renard2["fécondité"]) / 2: #test si la moyenne des fécondités est sup à 0.5
            créer_renard() # on crée le nombre de renards voulus sur la case

SyntaxError: invalid syntax (<ipython-input-3-2eef5b0e8fae>, line 1)

In [4]:
reproduction_des_lapins(lapin1, lapin2):
    if lapin1["sexe"] != lapin2["sexe"]:
        if 0.5 <= lapin1["fécondité"]*lapin2["fécondité"]:
            créer_lapin()

SyntaxError: invalid syntax (<ipython-input-4-5ee9d814025f>, line 1)

In [5]:
rencontre_renard_lapin(renard, lapin):
    if renard["efficacité"] + facteur_chance >= rand():
        lapin -> mort
        faim renard = 0

SyntaxError: invalid syntax (<ipython-input-5-de479c30b101>, line 1)

### Environnement

In [6]:
init_environnement(n):
    """On initialise une matrice carrée de taille n telle que une unité donne 100 mètres"""
    return (create array((n,n)), create array((n,n)), create array((n,n)))

SyntaxError: invalid syntax (<ipython-input-6-3e58581ed490>, line 1)

L'environnement est constitué de trois matrices :
 - matrice renard
 - matrice lapin
 - matrice carotte
 
Les matrices renard et lapin sont des matrices d'int où le chiffre indique le nombre d'animaux en question.

La matrice carotte est une matrice de rand() où .1 indique une unité de nourriture.

### Boucle principale

In [7]:
boucle principale():
    # pour chaque case avec un renard on regarde si le renard a un lapin ou un renard dans son entourage de Moore
    # si c'est le cas :
        # si il y a les deux :
            #on compare les niveaux de faim et d'excitation
        # il se déplace vers la case choisie
        # sinon il se déplace aléatoirement
    #pour chaque case avec un lapin on regarde si le lapin a une carotte ou un lapin dans son Moore
    #si c'est le cas :
        # si il y a les deux :
            #on compare les niveaux de faim et d'excitation
        # il se déplace vers la case choisie
        # sinon il se déplace aléatoirement
    #pour chaque case avec carotte on ajoute 0.01 au stock de carottes
    
    #résolution des interactions :
    #for e in [0,100]
        #for i in [0,100]
            #if matrice_renard[(e,i)] >= 1 and matrice_lapin[(e,i)] >= 1:
                #mort_lapin()
                #faim_renard_down()
            #if matrice_renard[(e,i)] >= 2
                #naissance_renard()
                #excitation_renard_down()
            #if matrice_lapin((e,i)) >= 2:
                #naissance_lapin()
                #excitation_lapin_down()
            #if matrice_lapin[(e,i)] >= 1 and matrice_carotte[(e,i)] >= 0.1
                #carotte_down()
                #faim_lapin_down()
            #if matrice_carotte[(e,i)] > 0
                #naissance_carrote_moore()
                

SyntaxError: invalid syntax (<ipython-input-7-4bbcef7e6c0b>, line 1)

### Mise en code préliminaire

In [38]:
#On réunira ici toutes les déclarations de variables globales
#On importera également nos bibliothèques ici

import numpy as np
import random as rd
import copy as copy
import uuid as uuid

#type(n) : int
#n est la taille de la matrice carrée
n = 100

#type(probabilite_presence_carotte) : float [0.00 ; 1.00]
#probabilite_presence_carotte est la probabilité qu'il n'y ait pas de carottes sur une case
probabilite_presence_carotte = 0.5

#type(esperance_vie_renard) : int
#esperance_vie_renard est un nb de jours
esperance_vie_renard = 1825 #environ 5 ans

#type(esperance_vie_lapin) : int
#esperance_vie_lapin est un nb de jours
esperance_vie_lapin = 2555 #environ 7 ans

#type(efficacite_renard) : float
#efficacite_renard est l'efficacité de chasse du renard, i.e. sa chance d'attraper le lapin
efficacite_renard_generale = 0.20 #basé sur des données réelles
def efficacite_renard_specifique():
    return rd.uniform(-0.1,0.1)

#type(efficacite_lapin) : float
#efficacite_lapin est un pondérateur fictif pour éviter un système mathématique trop prédominant, c'est le facteur chance naturel
def efficacite_lapin_specifique():
    return rd.uniform(-0.1,0.1)

#type(nb_renards_initial) : int
#nb_renards_initial le nombre initial de renards
nb_renards_initial = 500

#type(nb_lapins_initial) : int
#nb_lapins_initital le nombre initial de lapins
nb_lapins_initial = 1000

#type(M) : int
#M le range de l'entourage de Moore
M = 1

#type(maturite_sexuelle_renard) : int
#maturite_sexuelle_renard le nb de jours pour pouvoir s'accoupler
maturite_sexuelle_renard = 310 #donnée réelle, correspond à 10 mois

#type(temps_gestation_renard) : int
#temps_gestation_renard le nb de jours avant de mettre bas
temps_gestation_renard = 55 #donnée réelle

In [35]:
def init_matrice():
    a = np.empty((n,n), dtype=np.object_)
    a.fill([])
    a = np.frompyfunc(list,1,1)(a)
    return a

In [36]:
print(init_matrice())

[[list([]) list([]) list([]) ... list([]) list([]) list([])]
 [list([]) list([]) list([]) ... list([]) list([]) list([])]
 [list([]) list([]) list([]) ... list([]) list([]) list([])]
 ...
 [list([]) list([]) list([]) ... list([]) list([]) list([])]
 [list([]) list([]) list([]) ... list([]) list([]) list([])]
 [list([]) list([]) list([]) ... list([]) list([]) list([])]]


In [11]:
def init_matrice_carotte():
    return np.random.random((n,n))

In [12]:
matrice = init_matrice_carotte()
print(matrice)
print(matrice[1,0])

[[0.93784025 0.68015584 0.88396828 ... 0.77205877 0.77283976 0.11469355]
 [0.05859097 0.95157566 0.7342707  ... 0.69292043 0.78158329 0.05856404]
 [0.04198223 0.83171269 0.48368424 ... 0.2742416  0.26481938 0.14148025]
 ...
 [0.54885322 0.13091617 0.00866023 ... 0.487194   0.96177308 0.10160413]
 [0.94407483 0.94535728 0.9340767  ... 0.90521886 0.96563217 0.47872055]
 [0.4524353  0.5085679  0.38549322 ... 0.04853479 0.53296104 0.56483384]]
0.058590965948206786


In [13]:
def creation_liste_renards():
    cpt = 0 #type(cpt) : int
    renards = []
    while cpt < nb_renards_initial:
        cpt += 1
        renards.append(creation_renard())
    return renards

In [16]:
print(creation_liste_renards())

[(1032, False, 0.27492615725296465, 0.29109139084242, 0.17103316615643804, 0.6279954752013709, (False, 0, 0), (82, 92)), (88, False, 0.23869150281037516, 0.8239434149433407, 0.5240939849736955, 0.6516551219527648, (False, 0, 0), (66, 14)), (1191, False, 0.14809438566640173, 0.6605159387030453, 0.5418888189622398, 0.754050559916654, (False, 0, 0), (90, 78)), (1740, True, 0.1420405927964653, 0.8016287502934354, 0.8618443226423468, 0.41145069964134773, (False, 0, 0), (24, 9)), (36, False, 0.21030423526491418, 0.2562354398890545, 0.46681175179468193, 0.5488906662731264, (False, 0, 0), (33, 18)), (1449, True, 0.21205666858637795, 0.3562847634789251, 0.18269376497399636, 0.2287504030520947, (False, 0, 0), (23, 89)), (448, True, 0.10338670735411287, 0.5100660350797481, 0.42287225680774987, 0.4524916394326429, (False, 0, 0), (79, 39)), (1418, False, 0.19816165035372435, 0.3369771934280579, 0.6944855799303913, 0.04798836921832106, (False, 0, 0), (3, 75)), (425, False, 0.204469997217606, 0.57742

In [15]:
def creation_renard():
    uuid = uuid.uuid4()
    age = rd.randint(0,esperance_vie_renard)
    sexe = rd.choice([True, False]) #True correspond à femelle
    efficacite = efficacite_renard_generale + efficacite_renard_specifique()
    fecondite = rd.uniform(0.2,1.0)
    position = (rd.randint(0,n-1),rd.randint(0,n-1))
    faim = rd.random()
    excitation = rd.random()
    gestationnaire = (False, 0, 0) #tuple indiquant si le renard porte une portée ou non, il indique aussi le nombre de jours avant mise à bas
    type_agent = "renard"
    
    return (uuid, age, sexe, efficacite, fecondite, excitation, faim, gestationnaire, position, type_agent)

In [17]:
print(creation_renard())

(1804, False, 0.22583819824122134, 0.5275628396254213, 0.10000902837738535, 0.7841776024035658, (False, 0, 0), (13, 99))


In [18]:
def creation_liste_lapins():
    cpt = 0 #type(cpt) : int
    lapins = []
    while cpt < nb_lapins_initial:
        cpt += 1
        lapins.append(creation_lapin())
    return lapins

In [21]:
print(creation_lapins())

[(139, False, 0.019343219724512292, 0.6662565981238171, 0.3381372982496166, 0.2317569518531709, (False, 0), (56, 57)), (809, False, 0.0003473994484515519, 0.22048099918003708, 0.13120865882918709, 0.950821193327811, (False, 0), (33, 67)), (668, True, 0.02336083324860043, 0.5252411596339333, 0.7284151204233591, 0.6396576825897461, (False, 0), (74, 29)), (2446, False, 0.08860056982508022, 0.30775128290248494, 0.2836878756845369, 0.30993082280530926, (False, 0), (33, 35)), (2260, False, -0.021213873142525347, 0.43794941458523856, 0.31077339439077056, 0.2230580578402438, (False, 0), (49, 35)), (9, False, 0.042560917265514114, 0.3165766493106791, 0.10420714342687987, 0.485512848230894, (False, 0), (85, 35)), (910, True, -0.04151531833403164, 0.77349635613822, 0.6194029283544388, 0.29013222949292417, (False, 0), (93, 19)), (1936, True, 0.009693694115684812, 0.704580680449002, 0.00818189931538904, 0.8437874566723461, (False, 0), (8, 36)), (2163, True, -0.03015662713902416, 0.43062462278048186

In [20]:
def creation_lapin():
    """None -> lapin
    lapin : tuple[int, bool, float, float, float, float, tuple[bool, int], tuple[int, int]]"""
    uuid = uuid4()
    age = rd.randint(0, esperance_vie_lapin)
    sexe = rd.choice([True, False]) #True correspond à femelle
    efficacite = efficacite_lapin_specifique()
    fecondite = rd.uniform(0.2,1.0)
    position = (rd.randint(0,n-1),rd.randint(0,n-1))
    faim = rd.random()
    excitation = rd.random()
    gestationnaire = (False, 0) #tuple indiquant si le lapin porte une portée ou non, il indique aussi le nombre de jours avant mise à bas
    type_agent = "lapin"
    
    return(uuid, age, sexe, efficacite, fecondite, excitation, faim, gestationnaire, position, type_agent)

In [22]:
print(creation_lapin())

(1106, False, -0.0677255769575901, 0.46748013386060727, 0.28035342572139244, 0.8224634084577032, (False, 0), (91, 43))


In [23]:
def update_matrice_lapins(matrice_lapins, liste_lapins, valeur = 1):
    """Array(int) * list(lapin) * int -> Array(int)
    type(lapin) : tuple[int, bool, float, float, float, float, tuple[bool, int], tuple[int, int]]
    valeur = 1 ou valeur = -1"""
    for lapin in liste_lapins:
        _,_,_,_,_,_,_,position = lapin
        ligne, colonne = position
        matrice_lapins[ligne, colonne] += valeur
    return matrice_lapins

In [24]:
print(update_matrice_lapins(init_matrice_animal(), creation_lapins()))

[[0. 0. 0. ... 0. 0. 0.]
 [2. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 1.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [1. 0. 1. ... 0. 0. 0.]
 [0. 2. 0. ... 0. 1. 0.]]


In [25]:
def update_matrice_renards(matrice_renards, liste_renards, valeur = 1):
    """Array(int) * list(renard) * int -> Array(int)
    type(renard) : tuple[int, bool, float, float, float, float, tuple[bool, int], tuple[int, int]]
    valeur = 1 ou valeur = -1"""
    for renard in liste_renards:
        _,_,_,_,_,_,_,position = renard
        ligne, colonne = position
        matrice_renards[ligne, colonne] += valeur
    return matrice_renards

In [26]:
def nb_renardeaux(age3,age4,fec3,fec4):
    """donne le nombre de renardeaux dans une portée aléatoirement"""
    if age3 > maturite_sexuelle_renard and age4 > maturite_sexuelle_renard:
        if (fec3+fec4) / 2 >= 0.5:
            d = rd.randint(4, 5)
    return d

In [27]:
def mouvement_renard(matrice_renards, matrice_lapins, liste_renards, liste_lapins, renard):
    """Cette fonction à qui on fournit un renard va examiner tous les lapins et renards dans son entourage et déterminer ainsi son action.
    L'entourage considéré est de type Moore.
    """
    age, sexe, efficacite, fecondite, excitation, faim, gestationnaire, position = renard
    en_gestation, temps_gestation, nb_renardeaux = gestationnaire
    ligne, colonne = position
    
    liste_lapins_Moore = []
    liste_renards_Moore = []
    cpt = 0
    
    for i1 in range(-M,M+1):
        for i2 in range(-M,M+1):
            if i1 != i2 or i1 != 0:
                if matrice_lapins[colonne + i1, ligne + i2] > 0:
                    for lapin in liste_lapins:
                        _,_,_,_,_,_,_,position_proie = lapin
                        if position == (colonne + i1, ligne + i2):
                            liste_lapins_Moore.append(lapin)
                            del liste_lapins[cpt]
                        cpt += 1
                    cpt = 0
                if matrice_renards[colonne + i1, ligne + i2] > 0:
                    for renard in liste_renards:
                        sexe,_,_,_,_,_,_,position_partenaire = renard
                        if position == (colonne + i1, ligne + i2):
                            liste_renards_Moore.append(renard)
                            del liste_renards[cpt]
                        cpt += 1
                    cpt = 0
    
    if excitation >= faim and liste_renards_Moore != []:
        partenaire = rd.choice(liste_renards_Moore)
        
        age_partenaire, sexe_partenaire,_, fecondite_partenaire, excitation_partenaire,_,gestationnaire_partenaire, position_partenaire = partenaire
        ligne_partenaire, colonne_partenaire = position_partenaire
        en_gestation_partenaire, temps_gestation_partenaire, nb_renardeaux_partenaire = gestationnaire_partenaire
        
        matrice_renards[ligne, colonne] -= 1
        matrice_renards[ligne_partenaire, colonne_partenaire] += 1
        ligne = copy.copy(ligne_partenaire)
        colonne = copy.copy(colonne_partenaire)
        
        if sexe != sexe_partenaire:
            if sexe:
                en_gestation = True
                temps_gestation = temps_gestation_renard
                nb_renardeaux = nb_renardeaux(age, age_partenaire, fecondite, fecondite_partenaire)
            else:
                en_gestation_partenaire = True
                temps_gestation_partenaire = temps_gestation_renard
                nb_renardeaux_partenaire = nb_renardeaux(age, age_partenaire, fecondite, fecondite_partenaire)
            excitation = 0
            excitation_partenaire = 0
            
    elif faim > excitation and liste_lapins_Moore != []:
        proie = rd.choice(liste_lapins_Moore)
        
        
        
            
    