# Document de conception

## Système

#### Agents

##### Attributs

In [1]:
renard(âge, sexe, efficacité, fécondité, position, faim, excitation)
    renard = {"âge" : int, "sexe" : bool, "efficacité" : rand(), "fécondité" : rand(), (position_x, position_y), "faim" : float, "excitation" : float}
    renards = [renard1, renard2, renard3, renard4, renard5, ...]
lapin(âge, sexe, fécondité, position, faim)
    lapin = {"âge" : int, "sexe" : bool, "fécondité" : rand()}
    lapins = [lapin1, lapin2, lapin3, lapin4, lapin5, ...]

IndentationError: unexpected indent (<ipython-input-1-fecae7261b06>, line 2)

##### Procédures

In [ ]:
reproduction_des_renards(renard1, renard2):
    """Si deux renards sont sur la même case, cette fonction s'enclenche et fait apparaître des renardeaux sur la même case d'age 0"""
    if renard1["sexe"] != renard2["sexe"]: #On vérifie si le sexe des deux renards est différent
        if 0.5 <= (renard1["fécondité"]+renard2["fécondité"]) / 2: #test si la moyenne des fécondités est sup à 0.5
            créer_renard() # on crée le nombre de renards voulus sur la case

In [ ]:
reproduction_des_lapins(lapin1, lapin2):
    if lapin1["sexe"] != lapin2["sexe"]:
        if 0.5 <= lapin1["fécondité"]*lapin2["fécondité"]:
            créer_lapin()

In [ ]:
rencontre_renard_lapin(renard, lapin):
    if renard["efficacité"] + facteur_chance >= rand():
        lapin -> mort
        faim renard = 0

### Environnement

In [ ]:
init_environnement(n):
    """On initialise une matrice carrée de taille n telle que une unité donne 100 mètres"""
    return (create array((n,n)), create array((n,n)), create array((n,n)))

L'environnement est constitué de trois matrices :
 - matrice renard
 - matrice lapin
 - matrice carotte
 
Les matrices renard et lapin sont des matrices d'int où le chiffre indique le nombre d'animaux en question.

La matrice carotte est une matrice de rand() où .1 indique une unité de nourriture.

### Boucle principale

In [ ]:
boucle principale():
    # pour chaque case avec un renard on regarde si le renard a un lapin ou un renard dans son entourage de Moore
    # si c'est le cas :
        # si il y a les deux :
            #on compare les niveaux de faim et d'excitation
        # il se déplace vers la case choisie
        # sinon il se déplace aléatoirement
    #pour chaque case avec un lapin on regarde si le lapin a une carotte ou un lapin dans son Moore
    #si c'est le cas :
        # si il y a les deux :
            #on compare les niveaux de faim et d'excitation
        # il se déplace vers la case choisie
        # sinon il se déplace aléatoirement
    #pour chaque case avec carotte on ajoute 0.01 au stock de carottes
    
    #résolution des interactions :
    #for e in [0,100]
        #for i in [0,100]
            #if matrice_renard[(e,i)] >= 1 and matrice_lapin[(e,i)] >= 1:
                #mort_lapin()
                #faim_renard_down()
            #if matrice_renard[(e,i)] >= 2
                #naissance_renard()
                #excitation_renard_down()
            #if matrice_lapin((e,i)) >= 2:
                #naissance_lapin()
                #excitation_lapin_down()
            #if matrice_lapin[(e,i)] >= 1 and matrice_carotte[(e,i)] >= 0.1
                #carotte_down()
                #faim_lapin_down()
            #if matrice_carotte[(e,i)] > 0
                #naissance_carrote_moore()
                

### Mise en code préliminaire

In [106]:
#On réunira ici toutes les déclarations de variables globales
#On importera également nos bibliothèques ici

import numpy as np
import random as rd

#type(n) : int
#n est la taille de la matrice carrée
n = 100

#type(probabilite_presence_carotte) : float [0.00 ; 1.00]
#probabilite_presence_carotte est la probabilité qu'il n'y ait pas de carottes sur une case
probabilite_presence_carotte = 0.5

#type(esperance_vie_renard) : int
#esperance_vie_renard est un nb de jours
esperance_vie_renard = 1825 #environ 5 ans

#type(esperance_vie_lapin) : int
#esperance_vie_lapin est un nb de jours
esperance_vie_lapin = 2555 #environ 7 ans

#type(efficacite_renard) : float
#efficacite_renard est l'efficacité de chasse du renard, i.e. sa chance d'attraper le lapin
efficacite_renard_generale = 0.20 #basé sur des données réelles
def efficacite_renard_specifique():
    return rd.uniform(-0.1,0.1)

#type(efficacite_lapin) : float
#efficacite_lapin est un pondérateur fictif pour éviter un système mathématique trop prédominant, c'est le facteur chance naturel
def efficacite_lapin_specifique():
    return rd.uniform(-0.1,0.1)

#type(nb_renards_initial) : int
#nb_renards_initial le nombre initial de renards
nb_renards_initial = 500

#type(nb_lapins_initial) : int
#nb_lapins_initital le nombre initial de lapins
nb_lapins_initial = 1000

In [8]:
def init_matrice_animal():
    return np.zeros((n,n))

In [9]:
print(init_matrice_animal())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [30]:
def init_matrice_carotte():
    return np.random.random((n,n))

In [36]:
matrice = init_matrice_carotte()
print(matrice)
print(matrice[1,0])

[[0.56790043 0.20710714 0.7568296  ... 0.18662821 0.24648917 0.17114523]
 [0.07308749 0.26106488 0.11258999 ... 0.18900168 0.94796835 0.45352479]
 [0.6161675  0.16237236 0.83395654 ... 0.10398055 0.50123908 0.27208652]
 ...
 [0.30602366 0.85170911 0.95332698 ... 0.1327277  0.70947654 0.1835477 ]
 [0.18041972 0.39597994 0.77505438 ... 0.68664785 0.51128769 0.28178292]
 [0.80136932 0.36356103 0.05456804 ... 0.97298494 0.11926754 0.07994338]]
0.0730874894538055


In [99]:
def creation_renards():
    cpt = 0 #type(cpt) : int
    renards = []
    while cpt < nb_renards_initial:
        cpt += 1
        renards.append(creation_renard())
    return renards

In [100]:
print(creation_renards())

[(1299, True, 0.2, 0.5790350459044551, 0.3566480290300432, 0.25075272847366936, (False, 0), (34, 1)), (795, True, 0.2, 0.9969731633894658, 0.7060587541828377, 0.10739802509957141, (False, 0), (41, 95)), (1311, True, 0.2, 0.4387015277514749, 0.6687431365172977, 0.27041190054609143, (False, 0), (58, 57)), (1096, True, 0.2, 0.3346629559812868, 0.001194474496615583, 0.6726067778108477, (False, 0), (40, 9)), (883, False, 0.2, 0.9144952268372939, 0.15086991979717512, 0.8541927668790278, (False, 0), (100, 25)), (816, True, 0.2, 0.2547349962109584, 0.407360688938755, 0.6160430762475456, (False, 0), (11, 97)), (1131, False, 0.2, 0.31051837071062044, 0.8880933218553736, 0.9375185401212515, (False, 0), (3, 18)), (563, True, 0.2, 0.8201404519286049, 0.7787740675865317, 0.6561102202639757, (False, 0), (18, 64)), (32, True, 0.2, 0.7285783332400153, 0.6647209797584245, 0.7476020112447452, (False, 0), (59, 62)), (1155, True, 0.2, 0.6814257011717049, 0.21567746613383598, 0.7239238901718432, (False, 0),

In [110]:
def creation_renard():
    age = rd.randint(0,esperance_vie_renard)
    sexe = rd.choice([True, False]) #True correspond à femelle
    efficacite = efficacite_renard_generale + efficacite_renard_specifique()
    fecondite = rd.uniform(0.2,1.0)
    position = (rd.randint(0,n-1),rd.randint(0,n-1))
    faim = rd.random()
    excitation = rd.random()
    gestationnaire = (False, 0) #tuple indiquant si le renard porte une portée ou non, il indique aussi le nombre de jours avant mise à bas
    
    return(age, sexe, efficacite, fecondite, excitation, faim, gestationnaire, position)

In [88]:
print(creation_renard())

(1587, True, 0.2, 0.2602452360792869, 0.38334370877113433, 0.8348035133384094, (False, 0), (41, 8))


In [111]:
def creation_lapins():
    cpt = 0 #type(cpt) : int
    lapins = []
    while cpt < nb_lapins_initial:
        cpt += 1
        lapins.append(creation_lapin())
    return lapins

In [103]:
print(creation_lapins())

[(1156, True, -0.04795418824668862, 0.38181837019769493, 0.7525169027734192, 0.332285781391107, (False, 0), (91, 42)), (5, True, 0.010333785254795419, 0.3270982337823847, 0.207960942733733, 0.892381106667461, (False, 0), (94, 39)), (1850, True, -0.01849443707208631, 0.5132331995492465, 0.530054374360685, 0.4156020629087436, (False, 0), (31, 11)), (1916, False, -0.0923121468280213, 0.710819073830633, 0.0960692597977083, 0.20478343013975486, (False, 0), (80, 89)), (1884, True, -0.05963706606973778, 0.2904870363799555, 0.030862862966076543, 0.08248075197103755, (False, 0), (71, 38)), (1092, False, 0.08052163592852052, 0.4729757926065163, 0.5675699676010387, 0.8067774832680207, (False, 0), (52, 30)), (1737, True, -0.026678719656249197, 0.23464508172391163, 0.734837618283884, 0.8944760437963848, (False, 0), (69, 84)), (583, False, 0.04060237573293901, 0.41917147442797503, 0.36567870072967956, 0.1560550917074326, (False, 0), (55, 37)), (1077, False, 0.04479320023396838, 0.6197690848312034, 0

In [112]:
def creation_lapin():
    """None -> lapin
    lapin : tuple[int, bool, float, float, float, float, tuple[bool, int], tuple[int, int]]"""
    age = rd.randint(0, esperance_vie_lapin)
    sexe = rd.choice([True, False]) #True correspond à femelle
    efficacite = efficacite_lapin_specifique()
    fecondite = rd.uniform(0.2,1.0)
    position = (rd.randint(0,n-1),rd.randint(0,n-1))
    faim = rd.random()
    excitation = rd.random()
    gestationnaire = (False, 0) #tuple indiquant si le lapin porte une portée ou non, il indique aussi le nombre de jours avant mise à bas
    
    return(age, sexe, efficacite, fecondite, excitation, faim, gestationnaire, position)

In [97]:
print(creation_lapin())

(1481, True, -0.0841809489425492, 0.900589252254596, 0.8371945437054031, 0.00953499842465011, (False, 0), (78, 27))


In [116]:
def update_matrice_lapins(matrice_lapins, liste_lapins, valeur = 1):
    """Array(int) * list(lapin) * int -> Array(int)
    type(lapin) : tuple[int, bool, float, float, float, float, tuple[bool, int], tuple[int, int]]
    valeur = 1 ou valeur = -1"""
    for lapin in liste_lapins:
        _,_,_,_,_,_,_,position = lapin
        ligne, colonne = position
        matrice_lapins[ligne, colonne] += valeur
    return matrice_lapins

In [117]:
print(update_matrice_lapins(init_matrice_animal(), creation_lapins()))

[[0. 0. 0. ... 0. 0. 0.]
 [0. 1. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [118]:
def update_matrice_renards(matrice_renards, liste_renards, valeur = 1):
    """Array(int) * list(renard) * int -> Array(int)
    type(renard) : tuple[int, bool, float, float, float, float, tuple[bool, int], tuple[int, int]]
    valeur = 1 ou valeur = -1"""
    for renard in liste_renards:
        _,_,_,_,_,_,_,position = renard
        ligne, colonne = position
        matrice_renards[ligne, colonne] += valeur
    return matrice_renards

In [ ]:
def mouvement_renard(matrice_renards, matrice_lapins, liste_renards, liste_lapins):
    